#!/usr/bin/env bun
import { Bot } from "grammy";
import { loadConfig } from "./config.ts";
import { buildSpec } from "./spec/builder.ts";
import { writeSpec } from "./spec/writer.ts";
import { extractSpec } from "./llm/spec-extractor.ts";
import type { Context } from "grammy";

const config = loadConfig();

/**
 * Demo mode (no Telegram needed): writes one spec to the meta-repo inbox so the
 * end-to-end contract can be verified. Run: `bun run src/index.ts --demo-spec`
 */
if (process.argv.includes("--demo-spec")) {
  const spec = buildSpec({
    title: "Demo Note Taker",
    type: "cli",
    summary: "A tiny CLI to jot and list notes — generated by the bot demo path.",
    requirements: ["add a note", "list notes"],
    user: "demo",
    now: new Date().toISOString(),
  });
  const res = await writeSpec(spec, config);
  console.log(`✅ 데모 스펙 작성 완료 → ${res.dir} (committed=${res.committed})`);
  process.exit(0);
}

if (!config.botToken) {
  console.error("BOT_TOKEN이 비어 있습니다. .env.example을 .env로 복사해 설정하거나 --demo-spec으로 실행하세요.");
  process.exit(1);
}

const bot = new Bot(config.botToken);

// --- middleware: allowlist -------------------------------------------------
bot.use(async (ctx, next) => {
  if (config.allowlist.length === 0) return next(); // dev: open
  const id = ctx.from?.id;
  if (id && config.allowlist.includes(id)) return next();
  await ctx.reply("Sorry, you're not on the allowlist.");
});

// --- commands (A-0 minimal) ------------------------------------------------
bot.command("start", (ctx) =>
  ctx.reply(
    [
      "👋 I turn product ideas into specs.",
      "",
      "• Just describe what you want to build — I'll structure it into a spec.",
      "• /new <title> — quick draft, no AI",
      "• /help — details",
      "",
      config.aiEnabled ? "🧠 AI spec extraction: ON" : "⚠️ AI off (set CLAUDE_CODE_OAUTH_TOKEN to enable)",
    ].join("\n"),
  ),
);

bot.command("help", (ctx) =>
  ctx.reply(
    [
      "Describe a product in your own words and send it — I run it through Claude (your subscription) and write a structured spec to the meta-repo inbox.",
      "/spec <description> — same, explicitly.",
      "/new <title> — fast path, no AI.",
    ].join("\n"),
  ),
);

/** Run the AI extractor over free text and persist the resulting spec. */
async function handleSpecText(ctx: Context, text: string) {
  if (!text.trim()) return ctx.reply("Tell me what to build, e.g. “a CLI that renames photos by EXIF date”.");
  if (!config.aiEnabled) {
    return ctx.reply("AI spec extraction is off. Set CLAUDE_CODE_OAUTH_TOKEN, or use /new <title> for a quick draft.");
  }
  const note = await ctx.reply("🧠 Structuring your idea into a spec…");
  try {
    const spec = await extractSpec({
      conversation: text,
      user: ctx.from?.username ?? String(ctx.from?.id ?? "unknown"),
      now: new Date().toISOString(),
      model: config.aiModel,
    });
    await writeSpec(spec, config);
    await ctx.api.editMessageText(
      note.chat.id,
      note.message_id,
      `📝 Spec created: ${spec.slug}\nType: ${spec.type} · ${spec.requirements.length} requirement(s)\nWritten to the meta-repo inbox.`,
    );
    console.log(`AI 스펙 작성됨: ${spec.slug}`);
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    await ctx.api.editMessageText(note.chat.id, note.message_id, `⚠️ Couldn't build the spec: ${msg}`);
    console.error("extractSpec 실패:", e);
  }
}

bot.command("spec", (ctx) => handleSpecText(ctx, ctx.match ?? ""));

bot.command("new", async (ctx) => {
  const title = ctx.match?.trim();
  if (!title) return ctx.reply("Usage: /new <title>");
  const spec = buildSpec({
    title,
    user: ctx.from?.username ?? String(ctx.from?.id ?? "unknown"),
    now: new Date().toISOString(),
  });
  const res = await writeSpec(spec, config);
  await ctx.reply(`📝 Draft spec created: ${spec.slug}\nWritten to the meta-repo inbox.`);
  console.log(`스펙 작성됨: ${res.dir}`);
});

// Any non-command text is treated as a product description.
bot.on("message:text", (ctx) => {
  if (ctx.message.text.startsWith("/")) return; // unknown command — ignore
  return handleSpecText(ctx, ctx.message.text);
});

bot.catch((err) => console.error("봇 에러:", err));

console.log("봇 시작 중 (롱폴링)…");
bot.start();
