#!/usr/bin/env bun
import { Bot } from "grammy";
import { loadConfig } from "./config.ts";
import { buildSpec } from "./spec/builder.ts";
import { writeSpec } from "./spec/writer.ts";

const config = loadConfig();

/**
 * Demo mode (no Telegram needed): writes one spec to the meta-repo inbox so the
 * end-to-end contract can be verified. Run: `bun run src/index.ts --demo-spec`
 */
if (process.argv.includes("--demo-spec")) {
  const spec = buildSpec({
    title: "Demo Note Taker",
    type: "cli",
    summary: "A tiny CLI to jot and list notes — generated by the bot demo path.",
    requirements: ["add a note", "list notes"],
    user: "demo",
    now: new Date().toISOString(),
  });
  const res = await writeSpec(spec, config);
  console.log(`✅ wrote demo spec → ${res.dir} (committed=${res.committed})`);
  process.exit(0);
}

if (!config.botToken) {
  console.error("BOT_TOKEN is empty. Copy .env.example to .env and set it, or run with --demo-spec.");
  process.exit(1);
}

const bot = new Bot(config.botToken);

// --- middleware: allowlist -------------------------------------------------
bot.use(async (ctx, next) => {
  if (config.allowlist.length === 0) return next(); // dev: open
  const id = ctx.from?.id;
  if (id && config.allowlist.includes(id)) return next();
  await ctx.reply("Sorry, you're not on the allowlist.");
});

// --- commands (A-0 minimal) ------------------------------------------------
bot.command("start", (ctx) =>
  ctx.reply(
    [
      "👋 I collect product specs.",
      "",
      "/new <title> — start a spec (A-0: creates a draft immediately)",
      "/help — what I can do",
    ].join("\n"),
  ),
);

bot.command("help", (ctx) =>
  ctx.reply("Send /new <title>. In A-1 I'll ask follow-up questions for requirements, design, and constraints."),
);

bot.command("new", async (ctx) => {
  const title = ctx.match?.trim();
  if (!title) return ctx.reply("Usage: /new <title>");
  const spec = buildSpec({
    title,
    user: ctx.from?.username ?? String(ctx.from?.id ?? "unknown"),
    now: new Date().toISOString(),
  });
  const res = await writeSpec(spec, config);
  await ctx.reply(`📝 Draft spec created: ${spec.slug}\nWritten to the meta-repo inbox.`);
  console.log(`spec written: ${res.dir}`);
});

bot.catch((err) => console.error("bot error:", err));

console.log("Bot starting (long polling)…");
bot.start();
